### ISSUE TITLE
백그라운드에서 프로그라운드 서비스가 죽는 이슈

### ISSUE THREAD

**Issue by KDW03** [Volvo-Voice-Assistance/assistance-android#20]
@usersiyang 님
제 테스트 기기(OS 13) 기기에서 백그라운드로 서비스를 실행했을 때 잠시 후 죽는 Issue가 발생했습니다

 https://developer.android.com/about/versions/12/foreground-services?hl=ko

공식 문서를 보니 android 12 이상부터는 포그라운드 제한이 생겨서 WorkManager을 권장한다고 합니다
이 문제인 것 같은데 타깃하는 기기가 os 10으로 알고있어서 문제가 없다면 넘어가려고 하는데 
해당 기기로 백그라운드에서 문제가 없을지 확인 가능할까요?

**Comment by usersiyang** [comment]
@KDW03 안녕하세요. 현재 타겟하고 있는 기기가 OS 13이라서 발생하는 문제인 것 같습니다. 아직 확인은 못했는데 혹시 변경이 필요하다면 변경점이 많을까요? 확인 요청 드립니다.
